name: Release & APT Repo

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 
  pages: write    

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          
      - name: Install APT utilities
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev apt-utils

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Prepare APT Repository Structure
        run: |
          mkdir -p repo/dists/stable/main/binary-amd64
          mkdir -p repo/pool/main
          cp dist/*.deb repo/pool/main/
          
          cd repo
          # Gera o arquivo Packages
          dpkg-scanpackages --multiversion pool/main > dists/stable/main/binary-amd64/Packages
          gzip -9k dists/stable/main/binary-amd64/Packages
          
          # Gera o arquivo Release
          cd dists/stable
          echo "Origin: mexirica" > Release
          echo "Label: gpm" >> Release
          echo "Suite: stable" >> Release
          echo "Codename: stable" >> Release
          echo "Architectures: amd64 arm64" >> Release
          echo "Components: main" >> Release
          apt-ftparchive release . >> Release

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          export_armored: true

      - name: Sign APT Repo
        run: |
          gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --armor --detach-sign --clearsign -o repo/dists/stable/InRelease repo/dists/stable/Release
          gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --armor --detach-sign -o repo/dists/stable/Release.gpg repo/dists/stable/Release
          gpg --armor --export ${{ steps.import_gpg.outputs.keyid }} > repo/public-key.gpg

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: repo
          branch: gh-pages
          token: ${{ secrets.GH_PAT }}